### ISSUE TITLE
SuperGlue in feature matchig method

### ISSUE THREAD

**Issue by Alex-Beh** [SungJaeShin/Feature_matching#1]
May I know why SuperGlue is not under list of [feature matching method](https://github.com/SungJaeShin/Feature_matching?tab=readme-ov-file#2-methodology-to-apply-feature-matchingl)?

**Comment by SungJaeShin** [comment]
This repo aims for feature matching in challenging environments.
Here, a challenging environment means:
     (1) an illuminated indoor environment
     (2) an environment without many features
     (3) an environment where the general feature matching method is not done properly.

So, the goal of this repo is to check whether feature matching works well even in this environment, and as a result, the repo uses various methodologies.

The reason why SuperGlue was not added to the matching method here is as follows:
     (1) The reason for adding SuperPoint and SuperGlue-based matching results was to check whether learning method matching works well in a challenging environment
     (2) It was added to compare the results using the learning method with the methodology that did not use the learning method.
     (3) Since this repo aims to be implemented based on C++, we did not add a comparison group (SuperPoint + SuperGlue) written in Python
     (4) If I added it correctly, I added the SuperPoint model in C++, and it didn't look as good as the Python result, so I didn't apply SuperGlue. &rarr; In other words, it was only used as a comparison group for SuperGlue on Github [[22, 23]](https://github.com/magicleap/SuperGluePretrainedNetwork), which has already been released.

Thank you for your question!
If you have any further questions, please feel free to ask.
